### ISSUE TITLE
Webpack loader to extract i18n tagged templates

### ISSUE THREAD

**Issue by jkoudys** [skolmer/es2015-i18n-tag#24]
I've been struggling to get the i18n-tag-schema working to extract anything, but had a thought about using webpack to do this instead. It's an increasingly common pattern to simply apply a webpack loader via `require` (or a transpiled `import`, if that tickles your fancy) to build static assets, e.g. `require('css!mystyle.css');` in your top-level app.js, which your webpack config would see and bundle up as a static asset. Since translations are yet another static asset, why not let them go in the pipe too? 

Building it as a loader would abstract away decisions about building it into a gulp-task, auto-building, how to bundle it, etc., and all that complexity we have no reason to care about. It would also make it a lot easier to deal with different modules and loaders, since we could apply the loader after letting babel concat your modules together.

We'd probably want a couple loaders:
* find all the i18n-tagged template literals, and extract to json
* take the json, and convert to .po (for transifex, or loading into other sites, especially when you want translations available on a site using both client-side templates and server-side non-js templates).

Thoughts?

**Comment by skolmer** [comment]
Can you give some details about your issues with i18n-tag-schema?

The idea behind i18n-tag-schema is to generate a JSON schema file to help you write your translations in a strictly defined format. The JSON that has been created in the translation process can than easily be imported via webpack as a Javascript object and used as i18n-tag translation. 
This process is more about exporting meta data than importing translation data. 
Here is a simple example how you can use webpack to export your translations as a Javascript module if you are building a library: https://github.com/skolmer/es2015-i18n-tag#translations-as-commonjs-modules

**Comment by jkoudys** [comment]
Maybe I'm misunderstanding what it's for -- if I have a file that looks like:

```
import t from 'es2015-i18n-tag';
import { createElement as ce } from 'react';

const MyComponent = ({ name }) => (
  ce('section', {},
    ce('h1', {}, 'Welcome'),
    ce('p', {}, t`Hello, ${name}!`),
  )
);

export default MyComponent;
```

How could I extract the tagged templates, so I'd have a file that says `{ "Hello, ${0}!": "Hello, ${0}!" }`, and could use that to translate, build a .po file, etc.

**Comment by skolmer** [comment]
Taking your example, the tool would generate a JSON Schema that checks if you translation files contain the expected key `"Hello ${0}"` and also if the value of the key has a param `${0}`. This validation can be done with the i18n-tag-schema CLI or if you use an IDE with JSON Schema support (most modern IDEs support JSON Schema) it will provide autocompletion and validation of you translation files out of the box. The translation file should contain a `"$schema": "./schemafile.json"` property for the schema validation to work. More about IDE integration: https://github.com/skolmer/i18n-tag-schema#ide-integration
In vscode it will look like this: ![demo](https://raw.githubusercontent.com/skolmer/vscode-i18n-tag-schema/master/images/demo.gif) 
(check what happens when I open the translation.de.json file)

**Comment by skolmer** [comment]
@jkoudys I just realized that there is a serious problem with the current schema generator using your code. the import name is hardcoded in the schema generator and expected to always be i18n. keys like ```t`Hello, ${name}!` ``` will not be exported only ```i18n`Hello, ${name}!` ``` . I have to fix that in the next release.

**Comment by jkoudys** [comment]
Ah I see - that's the opposite side of what I'm looking to do. I want to inspect the javascript files statically and extract their translations and build a new translations file. Ultimately I'd want to export it as a .po file, or another format supported by transifex.

I could write it via babel-traverse, and grab every tagged template literal and extract its contents. Looking at http://astexplorer.net/#/6vMOJ1Ykxr , I could let you configure the tag-names you want extracted, then just grab each `TaggedTemplateExpression` with a matching `.tag.name` and export. Do you think this needs a new project, or could such a thing be part of this one? It's not the same tag feature, but it is a useful tool for enabling i18n-tags.

**Comment by skolmer** [comment]
i18n-tag-schema is using tools like babel-traverse, so most of the work is already being done. The library exports a JS module to export translation keys from files or directories. The export format is JSON but should be easy to translate to a .po file format. It would be nice to have an optional argument to export PO instead of JSON. A PR would be great 👍 
**Example Code:** https://github.com/skolmer/i18n-tag-schema#export-translation-keys
**API Documentation:** http://github.kolmer.net/i18n-tag-schema/globals.html#exporttranslationkeys

#### export format:
```js
[
  "hello world" ,  // the same as a msgid in PO
  "some other text",
  {
    "group": "common",  // the same as a msgctxt in PO
    "items": [
      "request password",  // the same as a msgid in PO
      "send message"
    ]
  }
  "some more text",
]
```

**Comment by jkoudys** [comment]
msgctxt? So i18n-tag supports contexts? I can't find examples in the codebase. How would you, for example, tell it that your string translation for 'orange' is a colour, or a fruit? Transifex supports translations with contexts (it's called `tc` usually ,when the t-function style is used), but I don't see how that could be done with the tag. Something like `i18n.context('fruit')`orange``, perhaps?

**Comment by skolmer** [comment]
I'm not sure how powerfull context is in transifex maybe I'm getting it wrong. 
I think i18n-tag has a similar feature, I called it [translation groups](https://github.com/skolmer/es2015-i18n-tag#translation-groups).

you can have a translation file like this:
```json
{
  "fruit": {
    "orange": "Orange"
  },
  "color": {
    "orange": "orange" 
  }
}
```
and in js you would write:
```js
i18n('color')`orange`
i18n('fruit')`orange`
```

**Comment by skolmer** [comment]
I had some time to create a new [postprocessor](https://github.com/skolmer/i18n-tag-schema#-postprocessors) feature that allows you to transform the format of the export. I added a simple [PO file format postprocessor](https://github.com/skolmer/i18n-tag-schema/blob/master/lib/postprocessors/po.js) that allows you to export all translation keys of your source directory into a simple .po file. If this doesn't match your requirements you can now write your own postprocessor npm package. It is a simple javascript function that takes the JSON export format shown above and transforms it to any other format.

**Comment by skolmer** [comment]
Import aliases are now supported by [i18n-tag-schema v2.4.0](https://github.com/skolmer/i18n-tag-schema/releases/tag/v2.4.0)

```js
import x, { i18nGroup as y } from 'es2015-i18n-tag' // alias names are now detected by the translation key exporter

@y('custom group')
export default class GroupedClass {
  val1 = x`my text`
  val2 = this.i18n`my grouped text`
}
```

**Comment by jkoudys** [comment]
Happy to leave this issue closed, I'm just wondering what a practical example of the decorator pattern you've used there would be? I can't think of a time I'd use a translation group like that; 99% of my translations are called outside classes (stateless components in React), but in practice I always see groups defined on a per-translation-string basis, and I can't think when I'd want it to be defined on the same group (or only one group). e.g. doing the fruit/colour example for "orange", I'd expect a group defined for both translations, not just one of them.

Can you think of a practical example for this?

**Comment by skolmer** [comment]
the idea to use one group per js module/class can help to contextualize your translations, it can help to avoid key collisions in larger project and makes large translation files more readable. this means you are using groups for all your translations. the default group is the name/path of the js module but an override could be "common.fruit" or just "color" or anything else to further contextualize the translation (in functional or technical terms).
lets say you write a react library where every single component should be translatable and you don't want the provided translations to affect other components within your lib. you could use the component file path (see [Babel generated file module groups](https://github.com/skolmer/es2015-i18n-tag#translation-groups)) as group name. you could expose an api function to the user that accepts translations in the known key/value object format and just apply it to this translation group to only change this one specific component.

It can also be used if you are lazy loading parts of your application. you could define a "main" group that contains all translations of your main app and a "admin" group that contains all keys of your admin interface and a "common" group that shares all translations in between. each groups configuration and translations (see [configuration groups](https://github.com/skolmer/es2015-i18n-tag#configuration-groups)) can be independently managed and wont affect each other. if the user visits the admin interface the application could lazy-load the admin translations merge it into the translation objects admin group and show the admin components to the user. It won't require the app to load all translations on initial app load for sub-pages the user might never visit.
