### ISSUE TITLE
Bug - Date not localized on Node V7.7.1

### ISSUE THREAD

**Issue by ManuelOverdijk** [skolmer/es2015-i18n-tag#34]
I've noticed that es2015-i18n-tag does not properly localize dates on node V7.7.1. I'm not sure if it's related to node, but in the the browser (chrome & chrome Canary) it works just fine with the same setup.

Setup:
```javascript
 i18nConfig({
        locales: 'nl-NL',
        number: {currency: 'EUR'},
        translations: translations['nl-NL'] || {}
    });
```
In the browser the expected output is for 
```javascript
i18n`${new Date()}:t(D)`
``` 
is "maandag 22 mei 2017", which is properly localized in the set locale. In Node v7.7.1 however, the output is till in English. Translating a string in node from my translations object works just fine, giving the suspicion the locale is properly set.

**Comment by skolmer** [comment]
In a Node.js environment you have to use the [Intl Polyfill](https://github.com/andyearnshaw/Intl.js#intljs-and-node) to add support for additional locales. If you haven't already installed Intl.js this should work:

`npm install intl`

```
import 'intl';  // import polyfill for ECMAScript Internationalization API
import 'intl/locale-data/jsonp/nl.js';  // import localization data for NL
```

**Comment by ManuelOverdijk** [comment]
Thanks for the quick response! Unfortunately the same result, also tried 'intl-locales-supported' which did not help

**Comment by skolmer** [comment]
To better understand the issue can you run `Intl.NumberFormat.supportedLocalesOf("nl-NL")` on application start and post the result here?

**Comment by ManuelOverdijk** [comment]
The result is an empty Array.

Full test code:
```
var i18nLibrary = require('es2015-i18n-tag');
var i18n = i18nLibrary.default;
var i18nConfig = i18nLibrary.i18nConfig;

i18nConfig({
    locales: 'nl',
    number: { currency: 'EUR' },
    translations: {}
});

require('intl');
require('intl/locale-data/jsonp/nl-NL.js');
Intl.NumberFormat.supportedLocalesOf("nl-NL");
```

**Comment by skolmer** [comment]
It looks like the locale data is not loaded as expected. Does it change if you use 
```js
var IntlPolyfill = require('intl');
require('intl/locale-data/jsonp/nl-NL.js');

Intl.NumberFormat   = IntlPolyfill.NumberFormat;
Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat; 

Intl.NumberFormat.supportedLocalesOf("nl-NL");
```

or 

```js
global.Intl = require('intl');
require('intl/locale-data/jsonp/nl-NL.js');

Intl.NumberFormat.supportedLocalesOf("nl-NL");
```

**Comment by ManuelOverdijk** [comment]
Thanks again for the quick input, really appreciated! With both of your provided options the output of `Intl.NumberFormat.supportedLocalesOf("nl-NL")` is [ 'nl-NL' ], however i18n still does not properly localise a date :(

**Comment by skolmer** [comment]
I just looked in to my tests where I'm using the Intl prolyfill and found this interesting line of code: https://github.com/skolmer/es2015-i18n-tag/blob/master/__tests__/es2015-i18n-tag.test.js#L8

It looks like I had to patch the "toLocaleString" functions of Date and Number which are used by the i18n lib to format those types. Can you give it a last try with the following code?
```js
global.Intl = require('intl');
require('intl/locale-data/jsonp/nl-NL.js');

Intl.__applyLocaleSensitivePrototypes();
```

**Comment by ManuelOverdijk** [comment]
Perfect, thank you very much!

For any experiencing the same issues, here is a full working example for Dutch:

```javascript
global.Intl = require('intl');
require('intl/locale-data/jsonp/nl-NL.js');

Intl.__applyLocaleSensitivePrototypes();

var i18nLibrary = require('es2015-i18n-tag');
var i18n = i18nLibrary.default;
var i18nConfig = i18nLibrary.i18nConfig;

i18nConfig({
    locales: 'nl-NL',
    number: {currency: 'EUR'},
    translations: {}
});
i18n`${new Date()}:t(D)` \\ should fully work now
```
