### ISSUE TITLE
Suggestion: Avoid the use of global configuration and objects

### ISSUE THREAD

**Issue by arabold** [skolmer/es2015-i18n-tag#43]
I found this library while looking for modern and easy ways of adding localization to my Node service. It's pretty much the only one which uses string tag functions and still supports standard variable replacements without inventing a new syntax. Brilliant! However, it doesn't seem to suite my use case as I'll have to handle multiple different translations in parallel, e.g. respond to parallel requests in different languages. Or maybe I just don't really understand how to use it?

I'm looking for something where I can instantiate multiple `i18n` string tag functions, each with a different locale and string table. I thus forked this repo locally and built something that works more like this:

```js
import { I18n } from "./i18";

const i18n = I18n.create({ locales: "de" });
console.log(i18n`Hello ${name}, you have ${amount}:c in your bank account.`);
// => Hallo Steffen, Sie haben US$ 1,250.33 auf Ihrem Bankkonto.
```

I feel this is a cleaner interface and better scoped. Would that be something to consider for a v2 of this lib? What are your thoughts about this?

**Comment by skolmer** [comment]
There is a feature called confirguration groups that allows you to use multiple i18n configurations in parallel: https://github.com/skolmer/es2015-i18n-tag#configuration-groups
For your usecase you might want to use the i18n tag function with the second argument to switch between multiple configurations ```i18n('translationGroup', 'configGroup')`string` ```

**Comment by skolmer** [comment]
If you have further questions regarding config groups feel free to reopen this issue.
