### ISSUE TITLE
update package.json main field 

### ISSUE THREAD

**Issue by hanc2006** [skolmer/es2015-i18n-tag#68]
Hi,
it's possible to update the main field value in packages.json to be compatible with the import map system.

`"main": "./dist/lib/index.js"`

instead of

` "main": "./dist/lib"`

**Comment by skolmer** [comment]
Sure, do you want to provide a pull request? 

NOTE: Please make sure if you commit your changes that you use `npm run commit` to create a commitizen friendly comment http://commitizen.github.io/cz-cli/. I you want it to be released after merging it should be of type `fix`
